[Prototype WIP] MultiprocessFileCache for efficient and easy cache with pytorch dataloader (num_workers>0)
pfnet/pfio pull request #128
Opened 2020-06-02 03:53 UTC by belltailjp

In case we combine pfio (+HDFS) with PyTorch DataLoader (num_workers>0), due to the following
reasons that are complexly related each other, I noticed that it is hard to make efficient/effective use of pfio FileCache easily.
* With HDFS, in my experience, setting num_workers>0 is almost always necessary for practical data loading performance
* The current pfio FileCache supports therad-safety but cannot be process-safe
* PyTorch DataLoader is designed to destroy all worker process at the end of each epoch

After a few serious consideration, I thought that implementing multi-process safe file cache is the simplest way to overcome it.

This PR is a prototype implementation of `MultiprocessFileCache`.
I think this is not perfectly efficient implementation, because
* each worker process opens the same file every time
* concurrency using flock
* the data is handed over to the main process by inter-process communication
* etc

Also, probably there is some unsafety.
However it shows approximately 2x speedup in my micro-benchmark (loading ImageNet zipped val images (including jpeg decode) with `num_workers=16`, cpu=24 setting) in PFN internal environment.

2020-06-03 06:17 UTC, belltailjp commented
I have made a few modifications based on an internal discussion
- Use a file for offset and lengths cache (as done in the current FileCache)
- Support what files to use for cache
- Fixed exclusive access control bug
As the result, it allows an intra-node shared cache file (sometimes useful e.g., in imbalanced distributed training setup), and cache file persistency.

In a distributed ImageNet training performance (ResNet50/fp16/8xV100/bs=32 per worker), I confirmed approximately 12% speedup in average, which is very significant.

2020-06-03 06:48 UTC, belldandyxtq commented
Is https://github.com/pfnet/pfio/blob/d37b16f55f87fc9217d22e6b0b23bee94b07e8b8/pfio/cache/file_cache.py#L285 helpful in this case? Or you want to also speed up the first epoch data loading

2020-06-03 07:00 UTC, belldandyxtq commented
Can you please merge to the latest master? the test fails due to #126 and is fixed by #127

2020-06-03 07:00 UTC, belltailjp commented
I think it's indeed very helpful feature.
In the current implementation, the same thing can be achieved by `MultiprocessFileCache(..., index_cache_file='xxxx', data_cache_file='yyy', cleanup=False)`.
`{index|data}_cache_file` arguments are intended to support an intra-node shared cache file, but by combining with `cleanup=False` the caches remain persisted.
If it's better to have the same interface (also better to control timing of persistency process), I think I can implement it, but something equivalent to `{index|data}_cache_file` should still be needed in the initializer for its original purpose, which may be a bit confusing if we have both.
\# Oh, btw it doesn't support what is equivalent to `FileCache.preload`..

2020-08-17 13:58 UTC, belltailjp commented
Hi, it's been quite a while, but I update the MultiprocessFileCache implementation. I think it's now ready for review.

* Similar `preserve` and `preload` interface to the existing FileCache.
* Test

2020-09-14 02:30 UTC, belldandyxtq requested changes
Thanks again for your great contribution on this very interesting PR. I have the following questions:
1. Can you please provide some examples on how this cache can be properly used with the `Pytorch DataLoader`? It can be in the docstring.

2. If I understand correctly, the reason why we do not keep the `fd` is to pickle to the subprocesses. But I am concerned that opening/closing the file for every single read usually significantly damage the I/O performance. Is there anyway to reduce the amount of opening/closing? I am not very sure about how exactly the `Pytorch DataLoader` works inside, but is it possible to do things like this:
1. close the fds in master after all the `put`, and set to None
2. fork
3. check the fds in the subprocesses, if it is None, open the fd
In this way we only need one read per subprocesses.

2020-09-14 02:30 UTC, belldandyxtq commented on pfio/cache/multiprocess_file_cache.py
> +        index_fd = os.open(self.index_file.name, os.O_RDWR)
ditto

2020-09-14 02:30 UTC, belldandyxtq commented on pfio/cache/multiprocess_file_cache.py
> +        fd = os.open(self.index_file.name, os.O_RDONLY)
ditto

2020-09-14 02:30 UTC, belldandyxtq commented on pfio/cache/multiprocess_file_cache.py
> +        index_fd = os.open(self.index_file.name, os.O_RDWR)
Do we close this?

2020-09-15 12:47 UTC, belltailjp commented on pfio/cache/multiprocess_file_cache.py
> +
It's not actually documented in `FileCache`. Should they be both documented?

2020-09-15 12:57 UTC, belltailjp commented
> Can you please provide some examples on how this cache can be properly used with the Pytorch DataLoader? It can be in the docstring.

I added it to the `MultiprocessFileCache` docstring.

> If I understand correctly, the reason why we do not keep the fd is to pickle to the subprocesses. But I am concerned that opening/closing the file for every single read usually significantly damage the I/O performance. Is there anyway to reduce the amount of opening/closing? I am not very sure about how exactly the Pytorch DataLoader works inside, but is it possible to do things like this:

Thanks for the advice! Indeed, it is possible to make sure to open and close the fds only once in each process. I applied this change (though I actually saw no performance improvement in a micro-benchmark).   
Also, dangling fd problem pointed out by your comments are resolved along together.

2020-09-16 03:21 UTC, belltailjp commented on pfio/cache/multiprocess_file_cache.py
> +        index_fd = os.open(self.index_file.name, os.O_RDWR)
All done in the recent fix :+1:

2020-09-18 08:00 UTC, belldandyxtq requested changes

2020-09-18 08:22 UTC, belltailjp commented on pfio/cache/multiprocess_file_cache.py
> +
Right! I forgot it, now I pushed the fix along with a new test case.

2020-09-18 11:15 UTC, belldandyxtq commented
/test

2020-09-18 11:15 UTC, belldandyxtq approved these changes

2020-09-18 11:23 UTC, merged