Introduce size limit to file caches
pfnet/pfio pull request #143
Opened 2021-02-08 02:42 UTC by belltailjp

This PR introduces size limitation (in bytes) of cache data file in `FileCache` and `MultiprocessFileCache`.

### Background

Since the file caches are essentially to make a local copy of the entire dataset, they can easily run out of local disk accidentally.
In order to deal with it, the current file caches already handle `errno=ENOSPC` properly, i.e., even when disk full it does not die but just warn without adding the data.

However in some situations this might not be sufficient:
- We want to keep sufficient amount of free space in local (say, GBs) for system stability
- In kubernetes environment, a pod which runs out of local disk will be Evicted *before actually getting ENOSPC*

### Functionality

In this PR, the `cache_size_limit` option is added to `FileCache` and `MultiprocessFileCache` respectively.
By default it is set `None`, which means no limitation. So is 0.

In case a valid number is specified, when the total amount of cache data file reaches to the limit, the cache will no longer accept further data addition by changing the cache mode to `frozen`.
The part of cache already built until then can be utilized as usual.

### Known issue

- When multiple `FileCache` or `MultiprocessFileCache` instances exist, there's still a risk for disk exhaustion
    - I think we can make it user's responsibility to set appropriate limitations to each of cache.
- Index file size is not taken into account
    - The file cache has index file which is an LUT for data position as well as data file
    - In this PR, only data file size is considered.
    - Usually size of indices is trivial compared to data (in ImageNet case, index=20MB vs data=34GB)

2021-02-08 03:25 UTC, kuenishi commented
Thank you for the PR. It's definitely a good idea, but I would like to argue three points.

1. It would be nicer if the behaviour of disk full and cache hits the limit both aligned. I admit that just warning is not enough for today's use cases, which was sufficient in Chainer era, but I want them aligned. I would suggest adding another knob to preserve old behaviour such as `warn_on_full=True`, by default it preserves old behaviour in case of either the cache hits the soft limit or disk full. If it's `False`.
2. I doubt freezing after cache hit limit being really effective. In case of `DistributedDataParallel`, only the partial amount of dataset will be cached, say 1/n (n=number of GPUs) which limits the cache hit rate. Say the task has 8 GPUs, it's cache hit rate is only 12.5% - how much does it improve end-to-end performance?
3. I would suggest implementing this feature in `NaiveCache` too by getting object size with `sys.getsizeof()` . See: https://stackoverflow.com/a/19865746 . It would definitely be useful, in case my question above is addressed, or in case of single process traning.

2021-02-08 04:06 UTC, belltailjp commented
For 1 and 3, that makes a lot of sense! I'd like to make changes soon.

For 2, in practice we do not have to worry about it.
In distributed training, we usually split the data into subsets evenly by the number of MPI processes and assign them 1-to-1 using the [`DistributedSampler`](https://pytorch.org/docs/stable/data.html#torch.utils.data.distributed.DistributedSampler). The sampler is created only once at the beginning of training and will be re-used over epochs.
This means that one MPI process and the `FileCache|MultiprocessFileCache` instance inside is made sure to be in charge of only the fixed 1/N subset of the whole dataset during its lifetime.
Therefore, as long as we use the `DistributedSampler` [which is in my understanding common](https://github.com/pytorch/examples/blob/master/imagenet/main.py#L217), the total amount of caches will never change regardless of the number of concurrency. So concurrency won't interfere the hit ratio.

2021-02-08 04:22 UTC, kuenishi commented
:+1: on 2. BTW as master CI is somewhat broken, I'll try to fix the broken window and tests will be after that.

2021-02-08 05:31 UTC, kuenishi commented
So, I would suggest splitting this idea to two patches. One is to add cache size limit to two classes preserving old behaviour, another is to add option to change the disk/cache-full behaviour to freezing the cache... but there's another point of discussion, is it good to freeze, when the cache is not complete. The meaning of being frozen is the cache is complete and consistent with the original data. Given that our main uses cases are that the dataset is split among distributed processes, it's an irregular case and the application developer doesn't assume it.

A good new behaviour would be choosing among "just warning", "ignore", or "throwing exception (and the program exit)". What do you think?

2021-02-08 08:18 UTC, kuenishi requested changes
Just to update PR status. Please re-request review after this gets review-ready again.

2021-02-15 08:26 UTC, belltailjp commented
> A good new behaviour would be choosing among "just warning", "ignore", or "throwing exception (and the program exit)". What do you think?

In this PR I implemented the "silent ignore" behavior which I haven't sufficiently clarified why:

The key principle for me is that, when using the cache API in my codes I think it is common to make it as transparent as possible; i.e., the code will work with no problem without cache, and works identically but faster with a cache, like in general memory or OS filesystem caches. Given that, I would expect that my code won't die even if no data can be added anymore **in case** I am aware of it (through explicitly passing the `cache_size_limit` option).
\# Of course, in the case of any serious unexpected problems it should definitely die, though.

For raising an exception, I'd be against it because the original motivation of this PR is to deal with the case where the script is completely killed (by whichever an ENOSPC or eviction in k8s). If the size-limitation API raises an exception, the problem remains just in a similar form.

Warning would be nicer; but I'm afraid of the screen being occupied with the same warning messages; Usually Python suppresses warnings repetition (show just the 1st one), but since this works on process-basis, in our common workloads (MPI and multi-processing) there will still be tons of warning messages filling up.

---

> there's another point of discussion, is it good to freeze, when the cache is not complete.

Right... Honestly speaking, I abused the freeze mechanism just because it is there and handy. I can make some sort of a dedicated flag for the new purpose, though it'll behave identically to the current `._frozen` for now.

The question now is that

> The meaning of being frozen is the cache is complete and consistent with the original data

is this clarified somewhere (or it's fine if you'd define it so now)? If so I won't violate.
Actually `preserve` can be called anytime regardless of cache build progress, which may technically allow existence of an incomplete-but-frozen cache.

2021-02-15 08:59 UTC, belltailjp commented
For (3) - implementing `cache_size_limit` in `NaiveCache`, it turns out to be quite difficult...
This is because `sys.getsizeof` does not follow the object reference tree. There is a recipe of calling it recursively,
https://docs.python.org/ja/3/library/sys.html#sys.getsizeof
but it cannot accept arbitrary user-defined types.
There could be some sort of hack (like [this](https://goshippo.com/blog/measure-real-size-any-python-object/) - seems to work quite nicely in pure python world), but the data held outside Python world cannot be detected, which is the case for torch.Tensor.

2021-02-16 01:53 UTC, kuenishi commented
/test

2021-02-16 01:56 UTC, kuenishi approved these changes
I think I understand all of your concerns. I didn't express the definition of being frozen and that was ambiguous in case the cache isn't complete. Let's think that being frozen and complete are both orthogonal state. Maybe it'd be nice if we have a property like `cache.is_complete`, but that should be another discussion. Discussion on behaviour on cache size full can be continued at #138.

So far it's all nice. Thanks!

2021-02-16 07:03 UTC, kuenishi commented
@belltailjp Can you fix CI test failure? It's just an annoying flake8 issue.
```

00:06:51.881572 STDOUT 1766] | py39 run-test: commands[1] \| flake8 chainerio pfio |  
-- | -- | --
00:06:52.372922 STDOUT 1766] | pfio/cache/file_cache.py:106:80: E501 line too long (80 > 79 characters) |  
00:06:52.400715 STDOUT 1766] | ERROR: InvocationError for command /repo/.tox/py39/bin/flake8 chainerio pfio (exited with code 1)


```

2021-02-16 07:57 UTC, kuenishi commented
/test

2021-02-16 08:11 UTC, merged