[WIP] Single cache file
pfnet/pfio pull request #145
Opened 2021-02-10 10:16 UTC by belltailjp

Currently file caches (FileCache and MultiprocessFileCache) save the cache information separately into index file and data file.
This PR is to propose to change it to single file.

The new cache file is formatted as:
- index part: (8 bytes sample offset + 8 bytes sample size) * N
- data part: (arbitrary size of binary data) * N

where N is the number of samples to cache.
This is actually completely equivalent to just concatenating the current index and data file.

## Background

### More strict cache size limitation (related to #143)
#143 will introduce limitation of cache data, however currently it is limited to data file only.
It is usually OK - as the index files are relatively negligible in most cases (e.g., ImageNet1K case 34GB vs 20MB), but as the number of parallelism grows the index file increases, which becomes relatively non-trivial, but they'll be out of limitation.
By unifying the index and data file into one file, we can constrain the cache size more strictly. 

### Easier handling
In case we want to fully utilize cache `preserve` and `preload` functionality, if the preserved cache is a single file it is easier to handle/manage.

### Performance concern

@kuenishi has pointed out that since in a single-file cache, every time we access to the cache it reads the file twice (to get index and actually data), which may increase chance of conflict in multi-process use.
To be studied.

2021-02-15 03:01 UTC, kuenishi commented
/test

2021-02-15 07:47 UTC, kuenishi commented
@belltailjp Tests passed. Is this still WIP?

2021-02-15 07:50 UTC, belltailjp commented
I wanted to try some micro-benchmarks to see if there's non-negligible performance regressions due to increased chance of file access concurrency in `MultiprocessFileCache`. :bowing_man:

2021-02-16 07:46 UTC, belltailjp commented
https://gist.github.com/belltailjp/eb6a98a799bf1a56bd42132b92db763b#file-result-md
I checked the performance by a simple micro-benchmark.
- Build a cached file with 1MB/sample * 32K samples (32GB total), then measure loading time by 16, 32, 64 and 128 parallel processes.
- Same for 32KB/sample * 1M samples

There are certain amount of fluctuations but I think it's OK to say no significant degradation (nor improvement) in performance.

2021-02-16 08:13 UTC, kuenishi requested changes
The code looks good, but please fix the conflict against #143 .

2021-02-16 09:43 UTC, kuenishi commented
/test

2021-02-16 09:49 UTC, kuenishi approved these changes

2021-02-16 10:10 UTC, merged